# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GPSLayers
                                 A QGIS plugin
 Собирает слои для GPS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-06-23
        copyright            : (C) 2021 by Travin Alexzander/Roslesinforg
        email                : travin1995@inbox.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GPSLayers class from file GPSLayers.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .GPS_Layer import GPSLayers
    return GPSLayers(iface)
